// import React from 'react';
import Img from '../image/add-image (1).png';
import React, { useState, useContext, useEffect } from 'react'
// import Message from './Message'
// import { Chatcontext } from '../Context/ChatContext'
import { Timestamp, doc, onSnapshot, updateDoc } from "firebase/firestore";
import { storage } from '../Firebase';
import { Authorization } from '../Context/AuthContext'
import { ChatContext } from '../Context/ChatContext'
import { db } from '../Firebase';
import { HiOutlinePhotograph  } from 'react-icons/hi';
import { ref, uploadBytes, uploadBytesResumable,getDownloadURL} from 'firebase/storage';
import {  arrayUnion } from "firebase/firestore";
import { v4  as uuid} from 'uuid';
const Input = () => {
// yh component kaam arha send real time chat-message

  const [text,settext]=useState("")
  const [img,setimg]=useState(null);
 const {currentuser}=useContext(Authorization)
 const {data}=useContext(ChatContext)

const handlesend= async()=>{
  // https://firebase.google.com/docs/firestore/manage-data/add-data#update_elements_in_an_array idhr se liya hai
if(img){
// {Database systems: UUIDs can be used as primary keys or unique identifiers for database records, ensuring that each record has a globally unique identifier. This is especially useful in distributed or replicated database environments.
  const storageRef= ref(storage,uuid());
  const uploadTask = uploadBytesResumable(storageRef,img)
  // This code is responsible for uploading the image to the specified storage location.
  // and storage isliye kiya because image storage mai hona chaiye upload
  // vo object ko store krta




  uploadTask.on(
    (error) => {
     
    }, 
    () => {
      getDownloadURL(uploadTask.snapshot.ref).then(async(downloadURL) => {
        await updateDoc(doc(db,"chats",data.chatId),{

          messages: arrayUnion({
            id:uuid(),
            text,
            senderId:currentuser.uid,
            date:Timestamp.now(),
            img:downloadURL
      }),
      });
    }
  );
}
)}
 // yh chaiye hoga na kuki combined id hogi vovala chat khulna chaiye na
  // await updateDoc(washingtonRef, {
    // regions: arrayUnion("greater_virginia")
  // });
else{
//   It updates a Firestore document using the updateDoc function, specifying the document location as doc(db, "chats", data.chatId). This points to the "chats" collection and the specific chat document identified by data.chatId.
// Within the document update, it adds a new element to the regions array using the arrayUnion function. This new element contains an object with properties id, senderId, and date, which are set to the values generated by the uuid function, the currentuser.uid, and the Timestamp.now() respectively.
// This code is responsible for updating the Firestore document with the new chat message details when there is no image attached.
 
  await updateDoc(doc(db,"chats",data.chatId),{

    messages: arrayUnion({
        id:uuid(),
        text,
        senderId:currentuser.uid,
        date:Timestamp.now()
  })
 
  })

}
}



  return (
    <>
      <div className='imputing'>
      <input className='texting' type='text' placeholder='Type something...' style={{ outline: 'none',paddingLeft: '20px'  }}   value={text}  onChange={(e)=>settext(e.target.value)}/>
      <div className='send'>
        {/* <input type='file' style={{dis}} */}

        <HiOutlinePhotograph  style={{ color: '#e27396', fontSize: '35px' ,cursor:'pointer' }} 
        onClick={(e)=>{
              const file = e.target.files && e.target.files[0];
              if (file) {
            setimg(file);
            }
            }}
            />

        <input type='file' style={{display:'none'}}/>
        <button className='butting' onClick={handlesend}>Send</button>
      </div>
      

      </div>
    </>
  )
}

export default Input;
